#service postgresql
version: "3.8"

networks:
  products-service:
    name: products-service

services:
  products-service:
    container_name: products-service
    build: .
    ports:
      - 8080:8080
    networks:
      - products-service
    depends_on:
      - postgresql
  postgresql:
    image: postgres:latest
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products
    ports:
      - "5432:5432"
    networks:
      - products-service
